--liquibase formatted sql

--changeset Vasiliy:1
CREATE TABLE IF NOT EXISTS notification
(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
chat_id BIGINT NOT NULL,
message TEXT not NULL,
data TIMESTAMP not NULL
);